### ISSUE TITLE
No image shown in 'Click Points' window

### ISSUE THREAD

**Issue by FrozenSilent** [Yujun-Shi/DragDiffusion#11]
Hello! Thanks for the amazing work! I have tried the webui, but after I upload the image in the left window, the middle window remains in a waiting state and does not display any interactive images. Do you have any clue about this problem?
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/31409366/5eda5335-2640-4c67-ba9c-5ae454044873)

**Comment by Yujun-Shi** [comment]
hello, actually, it's due to an update of pydantic library version. Simply downgrade the version of pydantic would help. Please refer to this issue: https://github.com/Yujun-Shi/DragDiffusion/issues/9
