### ISSUE TITLE
文件下载中断后，出现报错

### ISSUE THREAD

**Issue by xuyu666** [Yujun-Shi/DragDiffusion#12]
文件下载中断后，出现报错，请问您知道如何解决么？
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/1d55d37d-219f-4239-b4d4-2413cc87b3be)

**Comment by xuyu666** [comment]
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/459c590f-f2ad-4c76-99ea-da19de89bed5)

**Comment by Yujun-Shi** [comment]
您好，似乎huggingface在国内连接确实有点问题。可以考虑的方案是，首先用下面这个命令把stable diffusion 1.5 clone下来：
git clone https://huggingface.co/runwayml/stable-diffusion-v1-5

然后，用wget把这个repo里每个大文件都下载到对应位置。
最后load模型的时候用本地路径load

**Comment by xuyu666** [comment]
谢谢你的回复，我在from_pretrained中加入force_download=True后，多尝试几次貌似可以了哈哈哈。

**Comment by Nomination-NRB** [comment]
> 谢谢你的回复，我在from_pretrained中加入force_download=True后，多尝试几次貌似可以了哈哈哈。

你好，请问你是运行python drag_ui_real.py之后进入UI界面点击run的时候发生的报错吗
