### ISSUE TITLE
Could not load image

### ISSUE THREAD

**Issue by 780753368** [Yujun-Shi/DragDiffusion#14]
![32e663aeb6cf2cd4f0a3a4c84538781](https://github.com/Yujun-Shi/DragDiffusion/assets/72513578/b20f35cc-bd9c-40ce-9795-a008c676342b)
![d2b0d7e68554e0ee56aed4d707ee34d](https://github.com/Yujun-Shi/DragDiffusion/assets/72513578/8c49cb70-68d2-4889-9311-c6040ee544a6)
As shown in the picture, the code is stuck at this step. It took an hour to load the picture and it has not been loaded. The computer is equipped with a 10th generation i7+2060

**Comment by Yujun-Shi** [comment]
hello, pls refer to https://github.com/Yujun-Shi/DragDiffusion/issues/11

**Comment by Yujun-Shi** [comment]
Hello, I'm closing this issue. Should you have any more questions, please re-open it.
