### ISSUE TITLE
生成结果异常（掩码mask未起作用，同类物体同步变化）

### ISSUE THREAD

**Issue by xuyu666** [Yujun-Shi/DragDiffusion#16]
人脸经过复制后拼接作为输入图像，随后更改提示语句进行推理，出来的结果如下。
能给点建议么，因为有时候一张图像里面有很多重复类似的物体时，也会出现这样的情况。
![img_cat](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/19a05d70-45bc-4e79-b6d3-ad88d896eb9e)

![image](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/ebacab2e-7246-4ebe-887d-a825cf692b0d)

![image](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/7a7aaccb-66bf-497b-99d5-116756b51c15)

**Comment by danieltanhx** [comment]
try out a set of data(need to fine tune) instead of just one, i fine tuned my own lora model to expand the latent space so that this gradio app can modify it later

**Comment by Yujun-Shi** [comment]
你好 @xuyu666 ，我尝试了一下你这个例子，似乎我这边是可以的，你可以再试一下。顺便提一下，在我们新的release当中已经把lora训练集成到用户界面里了，可以直接在用户界面里训练lora哈。
<img width="1510" alt="image" src="https://github.com/Yujun-Shi/DragDiffusion/assets/31932863/22a8fd75-d669-4b74-a4fd-6eeba6d90e44">

**Comment by xuyu666** [comment]
好的哈，谢谢你~
