### ISSUE TITLE
按照步骤运行到run之后报错

### ISSUE THREAD

**Issue by Nomination-NRB** [Yujun-Shi/DragDiffusion#19]
我的步骤：
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/83486284/36386fba-afa5-48db-8211-9eb796c224ca)

报错结果：
![ST}8_KWTOAR19A 8U T_(WU](https://github.com/Yujun-Shi/DragDiffusion/assets/83486284/417cd84e-e4f9-447f-8715-ecf5e072adef)

是因为[stable-diffusion-v1-5](https://huggingface.co/runwayml/stable-diffusion-v1-5)模型没有下载吗

**Comment by Yujun-Shi** [comment]
对的，是因为国内连huggingface可能有点问题，经常就是会下载不了。具体可以follow我的readme最后部分Common Issues and Solutions里面写的，先手动把模型下载到local_pretrained_models这个文件夹（注意，这里下载的应该是一个文件夹，即一个huggingface repo，而不是单个文件），然后运行drag_ui_real.py这个文件。然后在界面中把Algorithm Parameters -> Base Model Config -> Diffusion Model Path这个参数改成你的本地模型的路径，然后就可以运行了。

**Comment by Nomination-NRB** [comment]
> 对的，是因为国内连huggingface可能有点问题，经常就是会下载不了。具体可以follow我的readme最后部分Common Issues and Solutions里面写的，先手动把模型下载到local_pretrained_models这个文件夹（注意，这里下载的应该是一个文件夹，即一个huggingface repo，而不是单个文件），然后运行drag_ui_real.py这个文件。然后在用户界面中把Algorithm Parameters -> Base Model Config -> Diffusion Model Path这个参数改成你的本地模型的路径，然后就可以运行了。
> 
> 同时还补充一点，在编辑的时候需要画一个mask指定哪些区域是可被编辑的，而剩下的区域需要保持不变。或者如果不想指定mask的话，就把Algorithm Parameters -> Drag Parameters-> lam设为0，即不使用任何正则项约束背景不变。

感谢回复！现在试试看，那个sd repo好大

**Comment by Nomination-NRB** [comment]
> 

已经可以正确运行了，非常感谢！
