### ISSUE TITLE
请问训练一个Lora是依据上传上来的图片吗

### ISSUE THREAD

**Issue by Nomination-NRB** [Yujun-Shi/DragDiffusion#20]
你好，我现在有这个疑惑：

训练的这个模型是不是**只依靠上传的这一张图片**，我可以一次上传**多张图片**来**训练**一个lora吗，因为在使用的过程中发现，拉动图片之后会有**失真**的情况

**Comment by Yujun-Shi** [comment]
你好，是的，就是基于“重建给定图片”这个目标来训练一个lora。目前在user interface里没有做一次上传多张图片来训练一个lora的功能。不过如果你想要这样做的话，可以把你的多张图片放到lora那个文件夹里面的某一个文件夹下，然后follow我上一个版本（v0.0.0）的readme来用lora/train_lora.sh训练一个lora。最后，在使用时不要用用户界面训练lora，而是直接指定lora_path为刚才用lora/train_lora.sh训练的lora。如果训练多张图片的lora，可能需要把lora的训练步数调高，这样才能完全拟合给定图片。

同时，对于一些失真的情况，可能可以通过follow我写的readme里面的“Explanation for parameters in the user interface”这一块，对某些参数进行调节来缓解。
或者把lora训练的步数调高可能也可以有效果。

**Comment by Nomination-NRB** [comment]
> 

好的，感谢详细的解释！

**Comment by Nomination-NRB** [comment]
> 你好，是的，就是基于“重建给定图片”这个目标来训练一个lora。目前在user interface里没有做一次上传多张图片来训练一个lora的功能。不过如果你想要这样做的话，可以把你的多张图片放到lora那个文件夹里面的某一个文件夹下，然后follow我上一个版本（v0.0.0）的readme来用lora/train_lora.sh训练一个lora。最后，在使用时不要用用户界面训练lora，而是直接指定lora_path为刚才用lora/train_lora.sh训练的lora。如果训练多张图片的lora，可能需要把lora的训练步数调高，这样才能完全拟合给定图片。
> 
> 同时，对于一些失真的情况，可能可以通过follow我写的readme里面的“Explanation for parameters in the user interface”这一块，对某些参数进行调节来缓解。 或者把lora训练的步数调高可能也可以有效果。

好的，感谢详细的解释！
