### ISSUE TITLE
can not train lora

### ISSUE THREAD

**Issue by Zyj1moreT** [Yujun-Shi/DragDiffusion#21]
I download all files from huggingface，but I find this error ： ValueError: Cannot load local_pretrained_models/diffusion because down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_k.weight expected shape tensor(..., device='meta', size=(320, 1280)), but got torch.Size([320, 768]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.

It’s my config.json fault？ how can I solve it

**Comment by Zyj1moreT** [comment]
I find all my parameters  passed to UNet2DConditionModel, but are not expected and will be ignored.  I can run the process，but I can‘t train lora.

**Comment by Zyj1moreT** [comment]
I just can’t train lora

**Comment by Yujun-Shi** [comment]
hello, it seems that your error message is not due to lora training, but because you cannot load the pretrained diffusion model. Please make sure you downloaded Stable Diffusion 1.5 in this link: https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main

**Comment by Zyj1moreT** [comment]
I down load all files，but I can‘t solve this problem. I download the config.json from safety_checker. when I train LoRA, I get this error:

The config attributes {'architectures': ['StableDiffusionSafetyChecker'], 'initializer_factor': 1.0, 'logit_scale_init_value': 2.6592, 'model_type': 'clip', 'projection_dim': 768, 'text_config': {'_name_or_path': '', 'add_cross_attention': False, 'architectures': None, 'attention_dropout': 0.0, 'bad_words_ids': None, 'bos_token_id': 0, 'chunk_size_feed_forward': 0, 'cross_attention_hidden_size': None, 'decoder_start_token_id': None, 'diversity_penalty': 0.0, 'do_sample': False, 'dropout': 0.0, 'early_stopping': False, 'encoder_no_repeat_ngram_size': 0, 'eos_token_id': 2, 'exponential_decay_length_penalty': None, 'finetuning_task': None, 'forced_bos_token_id': None, 'forced_eos_token_id': None, 'hidden_act': 'quick_gelu', 'hidden_size': 768, 'id2label': {'0': 'LABEL_0', '1': 'LABEL_1'}, 'initializer_factor': 1.0, 'initializer_range': 0.02, 'intermediate_size': 3072, 'is_decoder': False, 'is_encoder_decoder': False, 'label2id': {'LABEL_0': 0, 'LABEL_1': 1}, 'layer_norm_eps': 1e-05, 'length_penalty': 1.0, 'max_length': 20, 'max_position_embeddings': 77, 'min_length': 0, 'model_type': 'clip_text_model', 'no_repeat_ngram_size': 0, 'num_attention_heads': 12, 'num_beam_groups': 1, 'num_beams': 1, 'num_hidden_layers': 12, 'num_return_sequences': 1, 'output_attentions': False, 'output_hidden_states': False, 'output_scores': False, 'pad_token_id': 1, 'prefix': None, 'problem_type': None, 'pruned_heads': {}, 'remove_invalid_values': False, 'repetition_penalty': 1.0, 'return_dict': True, 'return_dict_in_generate': False, 'sep_token_id': None, 'task_specific_params': None, 'temperature': 1.0, 'tf_legacy_loss': False, 'tie_encoder_decoder': False, 'tie_word_embeddings': True, 'tokenizer_class': None, 'top_k': 50, 'top_p': 1.0, 'torch_dtype': None, 'torchscript': False, 'transformers_version': '4.22.0.dev0', 'typical_p': 1.0, 'use_bfloat16': False, 'vocab_size': 49408}, 'text_config_dict': {'hidden_size': 768, 'intermediate_size': 3072, 'num_attention_heads': 12, 'num_hidden_layers': 12}, 'torch_dtype': 'float32', 'transformers_version': None, 'vision_config': {'_name_or_path': '', 'add_cross_attention': False, 'architectures': None, 'attention_dropout': 0.0, 'bad_words_ids': None, 'bos_token_id': None, 'chunk_size_feed_forward': 0, 'cross_attention_hidden_size': None, 'decoder_start_token_id': None, 'diversity_penalty': 0.0, 'do_sample': False, 'dropout': 0.0, 'early_stopping': False, 'encoder_no_repeat_ngram_size': 0, 'eos_token_id': None, 'exponential_decay_length_penalty': None, 'finetuning_task': None, 'forced_bos_token_id': None, 'forced_eos_token_id': None, 'hidden_act': 'quick_gelu', 'hidden_size': 1024, 'id2label': {'0': 'LABEL_0', '1': 'LABEL_1'}, 'image_size': 224, 'initializer_factor': 1.0, 'initializer_range': 0.02, 'intermediate_size': 4096, 'is_decoder': False, 'is_encoder_decoder': False, 'label2id': {'LABEL_0': 0, 'LABEL_1': 1}, 'layer_norm_eps': 1e-05, 'length_penalty': 1.0, 'max_length': 20, 'min_length': 0, 'model_type': 'clip_vision_model', 'no_repeat_ngram_size': 0, 'num_attention_heads': 16, 'num_beam_groups': 1, 'num_beams': 1, 'num_channels': 3, 'num_hidden_layers': 24, 'num_return_sequences': 1, 'output_attentions': False, 'output_hidden_states': False, 'output_scores': False, 'pad_token_id': None, 'patch_size': 14, 'prefix': None, 'problem_type': None, 'pruned_heads': {}, 'remove_invalid_values': False, 'repetition_penalty': 1.0, 'return_dict': True, 'return_dict_in_generate': False, 'sep_token_id': None, 'task_specific_params': None, 'temperature': 1.0, 'tf_legacy_loss': False, 'tie_encoder_decoder': False, 'tie_word_embeddings': True, 'tokenizer_class': None, 'top_k': 50, 'top_p': 1.0, 'torch_dtype': None, 'torchscript': False, 'transformers_version': '4.22.0.dev0', 'typical_p': 1.0, 'use_bfloat16': False}, 'vision_config_dict': {'hidden_size': 1024, 'intermediate_size': 4096, 'num_attention_heads': 16, 'num_hidden_layers': 24, 'patch_size': 14}} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.

**Comment by Zyj1moreT** [comment]
I find the problem! thank U !
