### ISSUE TITLE
如何本地二次lora模型

### ISSUE THREAD

**Issue by xuyu666** [Yujun-Shi/DragDiffusion#23]
您好：
我目前按照“bash lora/train_lora.sh”指令lora了一次模型，但是我后续想在当前优化模型的基础上，进行下一次优化，想问一下如何更新代码比较方便~ 同时想问一下您的代码里clip微调有开放接口么哈哈哈
![批注 2023-08-03 092900](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/03e719d4-541d-47c5-a10d-d386e4e75cd5)

**Comment by Yujun-Shi** [comment]
您好：
首先，目前我已经把训练lora的功能整合到UI里面了，所以不需要再用脚本文件来训练lora了哈。

当然，目前我还是保留了用脚本文件训练lora的代码以防有人需要用脚本来训练lora。如果想要用脚本文件，并且接着之前训练好的lora继续优化，需要改一下lora/train_dreambooth_lora.py这个文件。就是提供一个选项能在微调的时候直接根据指示的路径load一个lora，而不是像现在一样随机初始化一个lora。

目前因为我发现finetune UNet的LoRA就够用了，所以暂时没有微调CLIP的接口哈。不过如果你想微调的话，在目前的代码中，如果想要继续用脚本训练lora，可以考虑改一下lora/train_dreambooth_lora.py这个文件（如果是使用用户界训练lora，请修改utils/lora_utils.py）。
