### ISSUE TITLE
A confusion between the formula and the code

### ISSUE THREAD

**Issue by Aziily** [Yujun-Shi/DragDiffusion#25]
Hello, I am trying to understand your excellent work

But as far as I am concerned, according to the formula in the paper as below
$h_i^{k+1}=\text{arg}\min||F_q(\hat{z_t}^{k+1})-F_{h_i^k}(z_t)||$
Is the code here should be
https://github.com/Yujun-Shi/DragDiffusion/blob/3a88d93e97cbb1863d73a98b577b639bd4020b8a/drag_utils.py#L31C33-L31C33
`f0 = F0[:, :, int(pi[0]), int(pi[1])]` instead of `f0 = F0[:, :, int(pi0[0]), int(pi0[1])]`?

I wonder if it is my wrong understanding, hope for your answer

**Comment by Yujun-Shi** [comment]
Hello, thanks for your interests in our work!
Actually, this is a typo in our report. The code is the correct implementation.
Thanks again for pointing out the typo in our report. We will revise this in our later version.
