### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by gaoshangle** [Yujun-Shi/DragDiffusion#27]
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/37358834/2ea28e96-d615-4275-86c8-0a4b8b0e8ae1)
 
anything wrong
for help !!!
thanks

**Comment by Yujun-Shi** [comment]
Hello, can you please also show the error message you got in the command line terminals? Thanks!

**Comment by gaoshangle** [comment]
感谢回复哈

终端运行
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/37358834/5f6402cf-c4c5-433c-a1e9-73d675630e0e)

前端访问显示
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/37358834/6b948ead-74c5-4935-971a-e1d445ed6089)

上传第一张图片后前端就会有报错信息，终端没有报错信息
（今天运行的是最新的代码）

**Comment by Yujun-Shi** [comment]
你好，我在想有没有可能是这张图片的问题。是不是你这个图片有一些不一样的格式？或者你可以尝试upload一下我在lora/samples里面放的那些样例图片看看会不会有一样的问题。

**Comment by gaoshangle** [comment]
使用lora/samples里面的图片还是有同样的问题

![image](https://github.com/Yujun-Shi/DragDiffusion/assets/37358834/3c622821-ebc7-4a1f-a96b-cfc91a4efbfe)

看stable-diffusion-webui项目中有同学这样修改的，在这个项目中怎么做类似的修改呢
[https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9132#issuecomment-1488638956](url)

再次感谢

**Comment by gaoshangle** [comment]
问题找到了，是代理的问题

检查系统代理
`
echo $http_proxy
echo $https_proxy
echo $ftp_proxy
`
清除代理
`
unset http_proxy
unset https_proxy
unset ftp_proxy
`
感谢🙇‍
