### ISSUE TITLE
for different aspect ratios,run error

### ISSUE THREAD

**Issue by gaoshangle** [Yujun-Shi/DragDiffusion#29]
https://github.com/Yujun-Shi/DragDiffusion/blob/00ca94ac1fa5cf80f013758c7c919cc8767d2710/utils/ui_utils.py#L277C22-L277C22

   This line of code up here, made some changes as follows:

       save_result = torch.cat([
        source_image * 0.5 + 0.5,
        torch.ones((1,3,25, 512)).cuda(),
        image_with_clicks * 0.5 + 0.5,
        torch.ones((1,3,25, 512)).cuda(),
        gen_image[0:1]
    ], dim=-2)

now, the program works normally
Is that correct ？？
thanks

**Comment by Yujun-Shi** [comment]
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/31932863/ba993339-9441-4a5c-a3ce-abc834ea57c1)
hello, here is the correct way to do it. Already fixed in my latest commit. Thanks!

**Comment by gaoshangle** [comment]
error again, shape  different


RuntimeError: Sizes of tensors must match except in dimension 3. Expected size 733 but got size 728 for tensor number 4 in the list.

![image](https://github.com/Yujun-Shi/DragDiffusion/assets/37358834/1c5a93ca-60f9-4194-bab5-60bbb06be56d)



Use this image to verify
![20230905-143542](https://github.com/Yujun-Shi/DragDiffusion/assets/37358834/26e1d4ef-2f46-4178-867d-2504c7063708)

thanks

**Comment by Yujun-Shi** [comment]
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/31932863/e70c7b96-a7b6-45bb-9b67-fbd31af8abef)
hello, I've updated the code, and it should be functioning normally, pls check :)

**Comment by Yujun-Shi** [comment]
And in this case, where the image is a bit complicated, you may train LoRA for a bit longer, say 300 steps.
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/31932863/115dcafe-41e4-4315-8329-ea8beaaa2e85)

**Comment by Yujun-Shi** [comment]
I'm closing this issue for now, feel free to re-open if you have any other questions.

**Comment by gaoshangle** [comment]
OK fine
thanks
