### ISSUE TITLE
"Edit Gen Image"功能加载lora 模型出错

### ISSUE THREAD

**Issue by xuyu666** [Yujun-Shi/DragDiffusion#30]
很高兴看到您加入的新功能，在尝试的过程中遇到Lora模型加载出错的情况，想请教下您如何处理~
流程如下：
1、提示路径未存在模型--》导入前端Lora按钮刚训练的Lora，模型格式不对。
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/168a655d-736a-4b15-8e8c-35d6a0e3a519)
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/d83f7c0c-87d8-4781-babc-98446c8738f9)

2、去moxin下载以SD1.5为基础模型的Lora文件，放入后并修改名字为lora.safetensors，还是不行。
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/8af0a980-bf23-42ff-a52a-07f4c6a6cc46)
[https://civitai.com/models/68297/industrial-style](lora模型链接)
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/218a23ba-0892-4a39-bcaf-23c50418c738)
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/4c2491c6-6999-4f08-b3e7-c819db0532e4)
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/fe5138cf-0cce-43aa-8697-40d4bfe5c452)

期待您的回复~

**Comment by Yujun-Shi** [comment]
hello, 我这边似乎是没有这个问题的。
比如，我把这个lora下载到一个文件夹./lora_arch
<img width="375" alt="image" src="https://github.com/Yujun-Shi/DragDiffusion/assets/31932863/203db91f-344a-463a-beb0-c7b50fe3c008">
然后我再生成，就是这个结果：
<img width="1512" alt="image" src="https://github.com/Yujun-Shi/DragDiffusion/assets/31932863/14f71c9d-0ba0-4a98-8860-903baa458b49">
看你这边的错误信息，感觉有可能是因为你那边的配置的库版本跟我的不太一样（可能是diffusers版本不太一样）？
可以先尝试检查一下配置的库的版本，或者重新clone一下代码，然后像我那个readme里面写的一样再用conda create -f environment.yaml来创一个新的环境。

**Comment by xuyu666** [comment]
谢谢您的回复，目前已经解决啦！！
祝好~
