### ISSUE TITLE
直接反演结果偏洋红色

### ISSUE THREAD

**Issue by xuyu666** [Yujun-Shi/DragDiffusion#39]
哈喽哥，最近在使用DragDiffusion的时候发现，单张真实图像经过Lora后，不采用Drag的方式出来（直接反演run），结果会比原图偏向洋红色（多张实验结果都是这样），想问下您有什么方法解决么~
输入图（左），输出图（右）
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/62f22f9f-fa80-4ce0-8601-306c7c75e978)

![image](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/5a8fb874-06a6-4a91-9fe4-e1cb301f0467)

![image](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/80ea4e42-a84f-4d1f-9b04-a94635092f82)

**Comment by Yujun-Shi** [comment]
哈喽，两个可能的解决思路哈：1）LoRA的训练步数稍微多一点；2）inversion strength稍微调小一点（比如0.6~0.7的样子）

**Comment by xuyu666** [comment]
谢谢，我尝试这两个解决思路后，效果仍然偏洋红色，想问下你使用的时候存在这样的现象么，能否展示下你那边的结果~
原图如下：
![source_image](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/6de8e1c3-e8ee-47ce-b661-58b56b0f4ef5)

**Comment by Yujun-Shi** [comment]
我刚才尝试了一下，我估计是因为图片的插值的问题。因为我这边每次输入一张图片之后，都会resize到512*512。估计是resize的时候引入的这个artifacts

**Comment by xuyu666** [comment]
谢谢你，我多尝试下512原分辨率的图。其实我有点怀疑是不是Stablediffusion框架自身的存在的偏移或者其训练数据的整体偏移哈哈<惊讶>
相关文章链接：
https://github.com/Sygil-Dev/sygil-webui/issues/457
https://www.reddit.com/r/StableDiffusion/comments/ydwnc3/good_news_vae_prevents_the_loopback_magenta_skew/?rdt=39381

**Comment by Yujun-Shi** [comment]
对，我确实比较倾向于认为可能是vae的问题。就是vae本身encode这个图片的过程也没有特别完美

**Comment by xuyu666** [comment]
针对这个问题，我做了以下实验：
1、直接VAE反演 --》输出存在红色偏移。
2、使用单张输入图对 VAE 的decoder进行微调，红色偏移消除。
3、将微调后的VAE加入SD过程，反演图恢复正常。--》说明采样过程影响较小？
4、经过编辑后，中间向量的变化导致最终的结果图仍然色彩不对应（尽管有 mask区域的损失监督）。

针对编辑过程改变中间向量，导致最终结果仍然效果不对的情况（即使对单张输入图进行VAE微调，使其能正确反演），你有什么好的建议么~

**Comment by xuyu666** [comment]
好的，谢谢你耐心的回复，这个文章我也有注意到，确实是vae自身上限的问题~
