### ISSUE TITLE
请问怎么配置用哪一块gpu?

### ISSUE THREAD

**Issue by zbtrs** [Yujun-Shi/DragDiffusion#40]
集群上有多张gpu，想配置用显存占用最少的

**Comment by Yujun-Shi** [comment]
你好，感谢关注我们的工作！
我不确定你想问的问题是不是：“集群有多个gpu，如果在运行时指定使用哪个gpu？”
如果是这个问题的话，可以使用类似如下命令：
CUDA_VISIBLE_DEVICES=3 python3 drag_ui.py
在该命令中，我们将使用第四块gpu
想使用其他gpu就用更换CUDA_VISIBLE_DEVICES后面的数字
