### ISSUE TITLE
有一个疑问

### ISSUE THREAD

**Issue by zbtrs** [Yujun-Shi/DragDiffusion#42]
请问为什么mask选中了手部，眼睛会崩掉呢？
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/32517549/87bbda37-998a-47f8-a20d-311a26855999)

**Comment by Yujun-Shi** [comment]
<img width="1054" alt="image" src="https://github.com/Yujun-Shi/DragDiffusion/assets/31932863/559290fa-ca47-4572-9980-2d415f98e3d0">
眼睛这一块可以参考这里
眼睛主要应该是vae的问题，可以试一下在base model config里面换一个vae

**Comment by zbtrs** [comment]
感谢解答！有些时候发现效果有点奇怪，请问是底模的问题吗？（一直用的默认的），
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/32517549/e144df6e-5ea9-48a6-aec7-547d243a55fb)

**Comment by Yujun-Shi** [comment]
对，一般来讲，这种全身照，脸部比较小的，stable diffusion都处理的不是很好。可能是因为脸部细节比较多，然后在整张图里占的面积又比较小，所以难处理。可能专门针对这个补充训练数据再训练一下stable diffusion可以缓解这个问题。
