### ISSUE TITLE
Lora 速度优化建议

### ISSUE THREAD

**Issue by xuyu666** [Yujun-Shi/DragDiffusion#43]
在**lora_utils.py**文件中，将这段代码移出“**Lora training循环**”中，貌似可提高速度的同时不影响精度~
![批注 2023-10-17 114312](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/d6bbc3e0-8dfd-459a-86ba-6d691ffded3a)

实验环境：
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/717e9e8d-c03d-47c7-b696-e97389bf28de)

原始：
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/8aa8a140-e53d-4491-a583-0165c6f6a817)
![image - 2023-10-17T113742 269](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/095c1844-850e-4ad3-8167-38d45db716de)
代码优化后：
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/0e2eeb89-31c3-4ce5-91eb-0d0792d2b04c)
![image - 2023-10-17T113532 789](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/d4d059f6-8ea9-44fe-9911-1b492ef0da8d)

Res矩阵（应该数值裁剪的差距）：
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/748ae959-a4a7-4560-9a0d-20f3502577c4)

**Comment by xuyu666** [comment]
更新内容：
vae的采样代码不可放在循环代码外，为了保证每次采样的随机性。

更正后如下：
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/8dae8451-1286-4061-8556-a1772a487cb0)

速度对比：
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/7d48e9a7-efce-4863-8b85-5f16111d95d0)
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/49869475/dc5eaf36-c0eb-46bf-be98-43e7e0c48229)

**Comment by cbh1733908441** [comment]
@xuyu666 请问能看看改进后的完整代码吗？image_transformed没有定义

**Comment by xuyu666** [comment]
对于这个情况，我的理解是过vae encoder这段代码可以移出循环外，因为权重和输入都没有改变。
