### ISSUE TITLE
The handle point always can not move to destination 

### ISSUE THREAD

**Issue by landian60** [Yujun-Shi/DragDiffusion#45]
![6e53d212-5ab3-41d6-b67b-dddf6ddbb2db](https://github.com/Yujun-Shi/DragDiffusion/assets/40920543/ce075ab0-7481-483e-bc2e-28f7616ba2c0)
What should I change the parameters?

**Comment by Yujun-Shi** [comment]
Hello, it seems that you didn't draw a mask here. And in our case, not drawing mask means every pixel will be regularized to be the same as the original image. In this case, there are two solutions: 1) draw a mask on the left most panel to specify the editable regions; 2) set the hyper-parameter "lam" to be 0, which means all pixels of the image are editable.

**Comment by Yujun-Shi** [comment]
Hi, I'm closing the issue for now. If you have further question, feel free to reopen it. Thanks!
