### ISSUE TITLE
PCA visualization

### ISSUE THREAD

**Issue by Yongssss** [Yujun-Shi/DragDiffusion#50]
Thanks for your excellent work. In Fig.2, you show the PCA visualization of UNet feature maps at different diffusion steps for two video frames. Which layer do you use for visualization? How many components do you use in PCA?

**Comment by Yujun-Shi** [comment]
Hi, thanks for your interests in our work! We visualize the UNet features of the penultimate upsampling block. Also, we use three components as RGB color space can only handle three channels.

**Comment by Yujun-Shi** [comment]
Hi, I'm closing this issue for now. Feel free to reopen it if you have further questions :)
