### ISSUE TITLE
Please optimize VRAM

### ISSUE THREAD

**Issue by lilcdj** [Yujun-Shi/DragDiffusion#51]
Sir, this is revolutionary work.
but 14G VRAM recommendation still hard. (I only have 12G with my 3060)

**Comment by Yujun-Shi** [comment]
Hello, thanks for your interests in our work. With current version of code, you may drag real input image with under 12G, please have a try :)

**Comment by Yujun-Shi** [comment]
Hello, I'm closing this issue for now. Feel free to reopen it if you have any other questions. Thanks!
