### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by zcdliuwei** [Yujun-Shi/DragDiffusion#9]
When I finish training the Lora model and run the following code：python drag_ui_real.py，
I encountered the following error message：
![image](https://github.com/Yujun-Shi/DragDiffusion/assets/36565076/9a1fb056-7af5-4704-820d-ec6ed6fa460b)
and the interactive interface has never responded

**Comment by zcdliuwei** [comment]
I have solved this problem

**Comment by gponsr** [comment]
> I have solved this problem

@zcdliuwei facing the same issue. Can you share how did you solve it?

**Comment by zcdliuwei** [comment]
> > I have solved this problem
> 
> @zcdliuwei facing the same issue. Can you share how did you solve it?

pip install pydantic==1.10.11
This problem seems to be caused by the excessively high version of pydantic
Hoping this helps

**Comment by Yujun-Shi** [comment]
thanks for spotting this bug, I have updated the environment.yaml so that pydantic version will be fixed at 1.10.11
